export const SETUP_INIT_USERDATA = 'SETUP_INIT_USERDATA';
export const SETUP_ADD_SUBUSER = 'SETUP_ADD_SUBUSER';
export const SETUP_SAVE_SUBUSER = 'SETUP_SAVE_SUBUSER';
export const SETUP_SAVE_MAINUSER = 'SETUP_SAVE_MAINUSER';


export const VIDEO_LIVE_INIT = 'VIDEO_LIVE_INIT';


export const DEVICES_QUERY = 'DEVICES_QUERY';



export const GROUPS_QUERY = 'GROUPS_QUERY';