export const SETUP_INIT_USERDATA = 'SETUP_INIT_USERDATA';
export const SETUP_ADD_SUBUSER = 'SETUP_ADD_SUBUSER';
export const SETUP_SAVE_SUBUSER = 'SETUP_SAVE_SUBUSER';
export const SETUP_SAVE_MAINUSER = 'SETUP_SAVE_MAINUSER';


export const VIDEO_LIVE_INIT = 'VIDEO_LIVE_INIT';


export const DEVICES_QUERY = 'DEVICES_QUERY';


export const CHANNELS_QYERY = 'CHANNELS_QYERY';



export const GROUPS_QUERY = 'GROUPS_QUERY';
export const GROUPS_SETTING_ADD = 'GROUPS_SETTING_ADD';
export const GROUPS_SETTING_DROP = 'GROUPS_SETTING_DROP';
export const GROUPS_SETTING_REMOVE = 'GROUPS_SETTING_REMOVE';
export const GROUPS_SETTING_DELETE_GROUP = 'GROUPS_SETTING_DELETE_GROUP';

export const USERS_QYERY = 'USERS_QYERY';